## defaults for _all_ profiles
[default]
address = "0.0.0.0"
## limits = { form = "64 kB", json = "1 MiB" }

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
## limits = { json = "10MiB" }